name: Build test
on :
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  # issue_comment:
  #   types: [created]
jobs:
  build-test:
    # if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && contains(github.event.comment.body, '/run-build-ci'))
    runs-on: focs-latest-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@focs
      - name: build
        run: |
          rm -rf build
          cmake -S . -B build
          cmake --build build -- -j$(nproc)
